name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm install -g @vscode/vsce
    - run: vsce package --out remote-adb-server.vsix
    - if: success() && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        path: remote-adb-server.vsix
